docker debug test

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -59,7 +59,13 @@ jobs:
             docker stop sonnim-server || true
             echo "Removing existing container..."
             docker rm sonnim-server || true
-            echo "Pulling new image..."
+            echo "Logging into ECR..."
+            $(aws ecr get-login --no-include-email --region ap-northeast-2)
+            echo "Pulling Docker image..."
             docker pull ${{ steps.login-ecr.outputs.registry }}/sonnim-server:latest
-#            echo "Running new container..."
-#            docker run -d --name sonnim-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/sonnim-server:latest
+            if [ $? -ne 0 ]; then
+            echo "Docker pull failed"
+            exit 1
+            fi
+            echo "Running new container..."
+            docker run -d --name sonnim-server -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/sonnim-server:latest
